import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Sidebar from "@/app/ui/sidebar";
import {ReactNode} from "react";
import {Providers} from "@/app/providers";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <Providers>
            <main className={"App"}>
                <Sidebar/>
                <div className={"pageContent"}>
                    {children}
                </div>
            </main>
        </Providers>
        </body>
        </html>
    );
}
